spring:
  profiles:
    active: local
---
spring:
  profiles: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
          proxy:
            host: squid
            port: 3128
    
server:
    port: 7070
